// EW-UI-5A1-B3 — Authoritative server save-intent orchestrator (PURE CORE).
//
// The complete, fail-closed ordering of a wizard save: validate → resolve actor → load dealer-bound
// runtime → assert identity → check revision → reprice ON THE SERVER → map → validate DTO → persist.
//
// PURE by construction: NO "use server", NO server-only, NO Supabase, NO React, NO route, NO fixture
// or default catalog, NO clock, NO randomness, NO direct database, and NO persistence class or
// gateway implementation. Every effect arrives through `WizardSaveIntentDeps`, so the ENTIRE ordering
// — including step 1 — is exercisable under plain `node:test` without importing a server-only module.
//
// ── WHY EVERY STEP IS INJECTED, INCLUDING VALIDATION ────────────────────────────
// `validateWizardSaveIntent` is pure and could be imported directly. It is injected anyway so that
// step 1 appears in the SAME observable call trace as steps 2-15. Validating before the orchestrator
// would move that ordering into the Server Action, where "malformed input is rejected before the
// actor is resolved" could only be asserted by reading source text rather than by executing it.
//
// `persist` is a FUNCTION seam, not the persistence service class. That is what keeps this module
// free of any persistence implementation: the caller decides which gateway backs it, and in B3 the
// only wiring that exists binds the disabled `notImplementedPersistenceGateway`.
//
// ── FAIL-CLOSED ─────────────────────────────────────────────────────────────────
// Every dependency call sits in its own guard. A thrown dependency becomes that STAGE's typed
// failure — never an escaped exception, never a later stage running anyway, and never a success.
// No internal reason (actor reason, runtime reason, mapper message, Supabase text) is ever returned.

import type { EstimateSaveActorContext, EstimateSaveActorContextResolution } from "@/lib/auth/estimate-save-actor-context";
import type { AuthoritativeWizardRuntimeConfiguration } from "@/lib/wizard-catalog/wizard-runtime-config";
import type { computeWizardPricingFromConfig } from "../pricing/compute-wizard-pricing-from-config";
import type { WizardPricingResult } from "../pricing/wizard-pricing-types";
import type {
  ConfigSaveMapperFailure, ConfigSaveMapperResult, mapWizardDraftToSaveRequestFromConfig,
} from "./estimate-save-mapper-from-config";
import type { EstimateSaveRequest } from "./estimate-save-dto";
import type { EstimateSaveValidationResult } from "./estimate-save-errors";
import type { validateEstimateSaveRequest } from "./estimate-save-validation";
import type { EstimateSaveActionResult, EstimateSaveServerContext } from "./estimate-save-orchestration-types";
import { ESTIMATE_SAVE_ACTION_ERRORS } from "./estimate-save-orchestration-types";
import type {
  WizardSaveIntentFailure, WizardSaveIntentResult, WizardSaveIntentValidation,
} from "./wizard-save-intent-types";

/**
 * Injected dependencies. Note what is NOT here: no dealer id, no user id, no role, no catalog, no
 * pricing config, no rank. Those are produced by `resolveActorContext` / `loadRuntimeConfig`, never
 * supplied by a caller — and `requestId` is a logging value only, generated by the server wrapper
 * because a pure module may not invoke randomness.
 */
export interface WizardSaveIntentDeps {
  readonly validateIntent: (raw: unknown) => WizardSaveIntentValidation;
  readonly resolveActorContext: () => Promise<EstimateSaveActorContextResolution>;
  readonly loadRuntimeConfig: (context: EstimateSaveActorContext) => Promise<AuthoritativeWizardRuntimeConfiguration>;
  readonly computePricing: typeof computeWizardPricingFromConfig;
  readonly mapSaveRequest: typeof mapWizardDraftToSaveRequestFromConfig;
  readonly validateSaveRequest: typeof validateEstimateSaveRequest;
  readonly persist: (request: EstimateSaveRequest, context: EstimateSaveServerContext) => Promise<EstimateSaveActionResult>;
  readonly requestId: string;
}

/**
 * Failure arms that carry no detail. Derived from the public union by EXCLUSION, so the three
 * detail-bearing failures are unreachable through this helper — attaching `save-validation-failed`
 * without its issues is a compile error rather than a review finding.
 */
type PlainFailure = Exclude<
  WizardSaveIntentFailure,
  "invalid-intent" | "save-mapping-failed" | "save-validation-failed"
>;

const failPlain = (failure: PlainFailure): WizardSaveIntentResult => ({ ok: false, failure });

export async function runWizardSaveIntent(
  raw: unknown,
  deps: WizardSaveIntentDeps,
): Promise<WizardSaveIntentResult> {
  // ── 1. Validate the untrusted intent. Nothing downstream runs on malformed input. ──
  let validation: WizardSaveIntentValidation;
  try {
    validation = deps.validateIntent(raw);
  } catch {
    return { ok: false, failure: "invalid-intent", issues: [{ path: "intent", code: "unreadable-input" }] };
  }
  if (!validation.ok) return { ok: false, failure: "invalid-intent", issues: validation.issues };
  const intent = validation.intent;

  // ── 2. Resolve the actor EXACTLY ONCE. ──
  let actor: EstimateSaveActorContextResolution;
  try {
    actor = await deps.resolveActorContext();
  } catch {
    return failPlain("actor-context-unavailable");
  }

  // ── 3. Map the actor failure. The internal reason never leaves this switch. ──
  if (!actor.ok) {
    switch (actor.reason) {
      case "unauthenticated":            return failPlain("unauthenticated");
      case "membership-read-failed":     return failPlain("actor-context-unavailable");
      case "staff-read-failed":          return failPlain("actor-context-unavailable");
      case "no-active-membership":       return failPlain("forbidden");
      case "permission-denied":          return failPlain("forbidden");
      case "tenant-context-unavailable": return failPlain("tenant-context-unavailable");
    }
  }
  const context = actor.context;

  // ── 4. Load the dealer-bound runtime configuration for THAT actor's tenant. ──
  let runtime: AuthoritativeWizardRuntimeConfiguration;
  try {
    runtime = await deps.loadRuntimeConfig(context);
  } catch {
    return failPlain("runtime-config-unavailable");
  }

  // ── 5. Every WizardRuntimeConfigFailure collapses here; the specific reason is never returned. ──
  if (!runtime.ok) return failPlain("runtime-config-unavailable");

  // ── 6. The configuration must describe the tenant the actor is authorized for, and no other. ──
  if (runtime.dealerId !== context.dealerId) return failPlain("tenant-context-unavailable");

  // ── 7. The client's expected revision must match the configuration actually loaded. A stale
  //       revision means the operator priced against a catalog that has since changed. ──
  if (intent.expectedConfigRevision !== runtime.lifecycle.currentRevision) {
    return failPlain("stale-config-revision");
  }

  // ── 8. Reprice ON THE SERVER, from the SERVER's runtime inputs only. The client sent no totals,
  //       no catalog, no pricing config and no rank — there is nowhere for it to have sent them. ──
  let pricing: WizardPricingResult;
  try {
    pricing = deps.computePricing(intent.draft, runtime.pricingConfig, runtime.catalog, runtime.shopRank);
  } catch {
    return failPlain("server-pricing-failed");
  }

  // ── 9. Pricing must be unambiguously complete. A partial/unavailable/error result carries null
  //       totals by contract, and an unresolved item means a selection produced no priced line. ──
  if (
    pricing.status !== "success" ||
    pricing.completeness !== "complete" ||
    pricing.errors.length !== 0 ||
    pricing.unresolvedItems.length !== 0
  ) {
    return failPlain("server-pricing-failed");
  }

  // ── 10. Map to the canonical DTO using the SAME draft and the EXACT runtime inputs. ──
  let mapped: ConfigSaveMapperResult;
  try {
    mapped = deps.mapSaveRequest({
      draft: intent.draft,
      pricingResult: pricing,
      pricingConfig: runtime.pricingConfig,
      catalog: runtime.catalog,
      shopRank: runtime.shopRank,
    });
  } catch {
    return { ok: false, failure: "save-mapping-failed", mappingCodes: ["mapping-failed"] };
  }

  // ── 11. Mapper CODES only. `ConfigSaveMapperIssue.message` is deliberately not forwarded. ──
  if (!mapped.ok) {
    const codes: ConfigSaveMapperFailure[] = mapped.issues.length > 0
      ? mapped.issues.map((i) => i.code)
      : [mapped.reason];
    return { ok: false, failure: "save-mapping-failed", mappingCodes: codes };
  }
  const request = mapped.request;

  // ── 12/13. Authoritative DTO validation BEFORE persistence is entered, so a DTO defect is never
  //           reported as a persistence-stage error. ──
  let dto: EstimateSaveValidationResult;
  try {
    dto = deps.validateSaveRequest(request);
  } catch {
    return { ok: false, failure: "save-validation-failed", saveIssues: [] };
  }
  if (!dto.ok) return { ok: false, failure: "save-validation-failed", saveIssues: dto.issues };

  // ── 14. Persist. dealerId and userId come from the actor context — never from the intent. ──
  let outcome: EstimateSaveActionResult;
  try {
    outcome = await deps.persist(request, {
      requestId: deps.requestId,
      dealerId: context.dealerId,
      userId: context.userId,
      idempotencyKey: intent.idempotencyKey,
    });
  } catch {
    return failPlain("persistence-failed");
  }

  // ── 15. Map the persistence result. The success arm is returned DIRECTLY — never nested inside an
  //        `ok: true` wrapper, which is what would make an "ok:true containing a failure" possible. ──
  if (outcome.ok) return outcome;
  switch (outcome.code) {
    case ESTIMATE_SAVE_ACTION_ERRORS.RPC_NOT_IMPLEMENTED:  return failPlain("persistence-unavailable");
    case ESTIMATE_SAVE_ACTION_ERRORS.DUPLICATE_SUBMISSION: return failPlain("persistence-conflict");
    default:                                               return failPlain("persistence-failed");
  }
}
