// DealerOS — Reputation Agent Runtime: Customer Engagement Integration (Phase E)
//
// Sprint 11D Phase E: connects the Reputation Agent runtime to the Customer
// Engagement dry-run layer.
//
// For WORK_COMPLETED events this module:
//   1. Wraps the Sprint 11C engagement plan (WorkCompletedReputationPlan)
//   2. Prepares a ReputationExecutionRequest for Phase 11E+
//   3. Prepares a future LINE dispatch payload (dry-run — no message sent)
//   4. Prepares a future agent execution request (dry-run — no AI called)
//   5. Returns WorkCompletedRuntimePlan as the unified typed result
//
// Security:
//   dealer_id comes from WorkCompletedReputationPlan.dealer_id, which is always
//   populated from getCurrentDealer() in the Sprint 11C engagement orchestrator.
//   This module never introduces a new dealer_id surface.
//   No LINE messages are sent.
//   No AI inference is executed.

import type { WorkCompletedReputationPlan } from "@/lib/reputation/reputation-engagement";
import type { ReputationExecutionRequest, ReputationActionPlan } from "./runtime-types";

// ─── Future LINE dispatch payload ────────────────────────────────────────────

/**
 * FutureLineDispatchPayload — describes the LINE message that WOULD be sent
 * after dealer approval and Phase 11E+ implementation.
 *
 * dispatch_deferred: true — permanently, in Sprint 11D.
 * message_text: null — populated by reputation_agent in Phase 11E+.
 */
export interface FutureLineDispatchPayload {
  purpose:           "review_request";
  customer_id:       string;
  /** Always from WorkCompletedReputationPlan.dealer_id — never from client input. */
  dealer_id:         string;
  platform:          string;
  review_url:        string | null;
  language:          "ja" | "en";
  /** Always true in Sprint 11D — actual dispatch is a Phase 11E+ concern. */
  dispatch_deferred: true;
  /** Generated by reputation_agent in Phase 11E+. Null until then. */
  message_text:      null;
}

// ─── Future agent execution request ──────────────────────────────────────────

/**
 * FutureAgentExecutionRequest — describes the reputation_agent request that
 * WOULD be sent to the AI Gateway after dealer approval and Phase 11E+ implementation.
 *
 * execution_deferred: true — permanently, in Sprint 11D.
 */
export interface FutureAgentExecutionRequest {
  agent_id:           "reputation_agent";
  task_type:          "review_request_generation";
  /** Always from WorkCompletedReputationPlan.dealer_id — never from client input. */
  dealer_id:          string;
  customer_id:        string;
  work_order_id:      string;
  /** Always true in Sprint 11D — execution is a Phase 11E+ concern. */
  execution_deferred: true;
}

// ─── WorkCompletedRuntimePlan ─────────────────────────────────────────────────

/**
 * WorkCompletedRuntimePlan — the full runtime dry-run result for a WORK_COMPLETED event.
 *
 * Extends WorkCompletedReputationPlan (Sprint 11C) by adding:
 *   - execution_request:       what the runtime WOULD execute (Phase 11E+)
 *   - action_plan:             steps, prompt metadata, compliance checklist
 *   - line_dispatch_payload:   LINE message structure (no content yet)
 *   - agent_execution_request: reputation_agent request (no inference yet)
 *
 * dealer_approval_required and execution_deferred are permanently typed as
 * literal `true`.
 */
export interface WorkCompletedRuntimePlan {
  /** Sprint 11C engagement plan — review request + LINE + agent readiness. */
  engagement_plan:          WorkCompletedReputationPlan;
  /** The execution request that would be submitted to the runtime (Phase 11E+). */
  execution_request:        ReputationExecutionRequest;
  /** Action plan produced by ReputationRuntime.buildActionPlan() — null if no destination. */
  action_plan:              ReputationActionPlan | null;
  /** Future LINE message structure (dry-run — no content, no send). */
  line_dispatch_payload:    FutureLineDispatchPayload;
  /** Future reputation_agent request (dry-run — no execution). */
  agent_execution_request:  FutureAgentExecutionRequest;
  /** Permanently true — no action proceeds without dealer approval. */
  dealer_approval_required: true;
  /** Permanently true in Sprint 11D — all execution deferred to Phase 11E+. */
  execution_deferred:       true;
  prepared_at:              string;  // ISO 8601
}

// ─── Plan builder ─────────────────────────────────────────────────────────────

/**
 * buildWorkCompletedRuntimePlan — wraps a Sprint 11C engagement plan with
 * Phase E runtime metadata.
 *
 * Pure function — takes pre-computed engagement plan and action plan.
 * No DB calls, no AI calls, no LINE sends.
 *
 * @param engagementPlan  From prepareWorkCompletedReputationPlan() (Sprint 11C)
 * @param actionPlan      From ReputationRuntime.buildActionPlan() — may be null
 * @param now             ISO 8601 timestamp from the caller
 */
export function buildWorkCompletedRuntimePlan(
  engagementPlan: WorkCompletedReputationPlan,
  actionPlan:     ReputationActionPlan | null,
  now:            string,
): WorkCompletedRuntimePlan {
  const { event, dealer_id } = engagementPlan;

  // Derive the review destination from the prepared review request (if ready)
  const preparedDest = engagementPlan.review_request_readiness.prepared_request?.destination;

  const executionRequest: ReputationExecutionRequest = {
    task_type:             "review_request_generation",
    customer_id:           event.customer_id,
    work_order_id:         event.payload.work_order_id,
    completion_report_id:  event.payload.completion_report_id,
    service_summary:       event.payload.services_performed.join(", "),
    destination: preparedDest ?? {
      id:           "",
      dealer_id:    dealer_id,
      platform:     "google",
      label:        "Google",
      review_url:   null,
      enabled:      false,
      available_now: false,
    },
    language_preference:   "ja",
  };

  const linePayload: FutureLineDispatchPayload = {
    purpose:           "review_request",
    customer_id:       event.customer_id,
    dealer_id,
    platform:          executionRequest.destination.platform,
    review_url:        executionRequest.destination.review_url,
    language:          "ja",
    dispatch_deferred: true,
    message_text:      null,
  };

  const agentRequest: FutureAgentExecutionRequest = {
    agent_id:           "reputation_agent",
    task_type:          "review_request_generation",
    dealer_id,
    customer_id:        event.customer_id,
    work_order_id:      event.payload.work_order_id,
    execution_deferred: true,
  };

  return {
    engagement_plan:          engagementPlan,
    execution_request:        executionRequest,
    action_plan:              actionPlan,
    line_dispatch_payload:    linePayload,
    agent_execution_request:  agentRequest,
    dealer_approval_required: true,
    execution_deferred:       true,
    prepared_at:              now,
  };
}

// ─── Plan summary helper ──────────────────────────────────────────────────────

/**
 * summarizeRuntimePlan — one-line summary for logging or debug output.
 * Does not include sensitive data.
 */
export function summarizeRuntimePlan(plan: WorkCompletedRuntimePlan): string {
  return [
    `engagement=${plan.engagement_plan.overall_readiness}`,
    `action_plan=${plan.action_plan ? "ready" : "null"}`,
    `line=deferred`,
    `agent=deferred`,
    `dealer_approval_required=${plan.dealer_approval_required}`,
  ].join(", ");
}
