// DealerOS — AI Orchestration Engine: Plan Bridge Runner (Sprint 11L Phase A)
//
// Orchestrates the complete live bridge run for one AI execution plan.
//
// Run order per plan:
//   1. Build runtime context from live request (reuses plan-runner.ts builder)
//   2. Build parallel step groups (reuses step-runner.ts)
//   3. For each step in topological order:
//      a. Run dry-run step validation (deps, feature gate, approval gate check)
//      b. If blocked: record failure, continue to count blocked steps
//      c. If skipped (optional): record as skipped
//      d. If validated or blocked_approval: run live bridge lifecycle preparation
//      e. If approval gate triggered: build pause record, stop chain
//      f. Write output key placeholders for downstream steps
//   4. Compute overall plan state
//   5. Return AIOrchestratorLiveBridgeResult
//
// Security rules:
//   - dealer_id always from getCurrentDealer() — injected in AILiveRuntimeRequest
//   - agent_context always pre-built by the calling server action
//   - No DB calls inside this module
//   - No external API calls
//
// Async — calls runStepBridgeLifecycle() which calls agent.initialize().

import {
  getWorkflowSpec,
  resolveWorkflowPolicy,
}                                      from "../workflow-registry";
import {
  buildExecutionPlan,
}                                      from "../orchestrator-types";
import {
  buildDefaultFailureStrategy,
}                                      from "../failure-strategy";
import {
  buildParallelGroups,
  buildGroupIdForStep,
  runStepDryRun,
}                                      from "./step-runner";
import {
  writeFeedOutputKeys,
}                                      from "./cross-agent-feed";
import {
  buildInitialPlanState,
  buildInitialExecutionRecord,
  transitionStepState,
  recordStepResult,
  computeOverallPlanState,
  getCompletedStepIds,
}                                      from "./runtime-state";
import {
  runStepBridgeLifecycle,
}                                      from "./step-bridge";
import {
  buildApprovalPauseRecord,
  computePendingStepIds,
}                                      from "./approval-pause-handler";
import {
  DEFAULT_BRIDGE_POLICY,
}                                      from "./bridge-types";
import type {
  AILiveRuntimeRequest,
  AIStepBridgeResult,
  AIOrchestratorLiveBridgeResult,
  AIExecutionBridgeContext,
  AIExecutionBridgePolicy,
  AIApprovalPauseRecord,
}                                      from "./bridge-types";
import type { AIExecutionBridgeState } from "./bridge-types";
import type { AIRuntimePlanState }     from "./runtime-state";

// ─── Step-level bridge context builder ───────────────────────────────────────

function buildStepBridgeContext(
  request:    AILiveRuntimeRequest,
  plan_id:    string,
  step_id:    string,
  execution_id: string,
): AIExecutionBridgeContext {
  return {
    execution_id,
    dealer_id:      request.dealer_id,
    plan_id,
    step_id,
    workflow_id:    request.workflow_id,
    trace_id:       request.trace_id ?? `trace_${plan_id}`,
    execution_mode: "live",
    agent_context:  request.agent_context,
    input_payload:  {},  // Sprint 11L: no real input data; Sprint 11M will populate
    active_features: request.active_features,  // Sprint 11M: forwarded to readiness guard
  };
}

// ─── Overall state derivation ────────────────────────────────────────────────

function derivePlanBridgeState(
  plan_state:      AIRuntimePlanState,
  has_step_failed: boolean,
  has_approval_pause: boolean,
  all_prepared:    boolean,
): AIExecutionBridgeState {
  if (has_step_failed)      return "failed";
  if (has_approval_pause)   return "awaiting_approval";
  if (all_prepared)         return "ready";
  return computeOverallPlanState(plan_state.step_records);
}

// ─── Plan bridge runner ───────────────────────────────────────────────────────

/**
 * runPlanLiveBridge — orchestrates live bridge lifecycle preparation for a full plan.
 *
 * dealer_id must come from getCurrentDealer() in the calling server action.
 * agent_context must be pre-built by createAgentContext() in the calling server action.
 * plan_id should be a UUID generated by the calling server action.
 */
export async function runPlanLiveBridge(
  request:  AILiveRuntimeRequest,
  plan_id:  string,
  now:      string,
): Promise<AIOrchestratorLiveBridgeResult> {
  // Look up workflow spec
  const spec = getWorkflowSpec(request.workflow_id);
  if (!spec) {
    return buildFailedBridgeResult(
      plan_id,
      request,
      `Workflow "${request.workflow_id}" not found in registry`,
      now,
    );
  }

  // Resolve effective execution policy
  const base_policy      = resolveWorkflowPolicy(request.workflow_id);
  const effective_policy = request.policy_overrides
    ? { ...base_policy, ...request.policy_overrides }
    : base_policy;

  // Resolve bridge policy
  const bridge_policy: AIExecutionBridgePolicy = request.bridge_policy
    ? { ...DEFAULT_BRIDGE_POLICY, ...request.bridge_policy }
    : DEFAULT_BRIDGE_POLICY;

  // Build the execution plan from step templates
  const plan = buildExecutionPlan(
    plan_id,
    request.dealer_id,
    request.workflow_id,
    request.trigger_event,
    request.trigger_payload,
    spec.step_templates,
    now,
  );

  // Build failure strategy (used for dry-run step validation)
  const failure_strategy = buildDefaultFailureStrategy(request.workflow_id);

  // Build parallel groups for topological ordering
  const parallel_groups = buildParallelGroups(plan.steps, effective_policy.max_parallel_steps);

  // Sort steps in topological order (depth 0 first)
  const depthMap = new Map<string, number>();
  for (const g of parallel_groups) {
    for (const sid of g.step_ids) {
      depthMap.set(sid, g.depth);
    }
  }
  const sorted_steps = [...plan.steps].sort((a, b) => {
    const da = depthMap.get(a.step_id) ?? 0;
    const db = depthMap.get(b.step_id) ?? 0;
    return da - db;
  });

  // Build runtime context for dry-run validation
  const dry_run_context = {
    dealer_id:        request.dealer_id,
    plan,
    policy:           effective_policy,
    failure_strategy,
    execution_mode:   "dry_run" as const,
    active_features:  request.active_features,
    step_outputs:     {} as Record<string, unknown>,
    trace_id:         request.trace_id ?? `trace_${plan_id}`,
    created_at:       now,
  };

  // Initialize in-memory plan state
  let plan_state = buildInitialPlanState(
    plan_id,
    request.dealer_id,
    request.workflow_id,
    now,
  );

  // Results accumulator
  const step_results:       AIStepBridgeResult[] = [];
  const completed_step_ids  = new Set<string>();
  let   step_outputs         = { ...dry_run_context.step_outputs };
  let   approval_pause:      AIApprovalPauseRecord | null = null;
  let   has_step_failed      = false;

  for (const step of sorted_steps) {
    // Stop processing if the plan is paused at an approval gate
    if (approval_pause !== null) break;

    const parallel_group_id = buildGroupIdForStep(step.step_id, parallel_groups);
    const execution_id      = `exec_${plan_id.slice(0, 8)}_${step.step_id}`;

    // Build and register an execution record for this step
    const exec_record = buildInitialExecutionRecord(
      request.dealer_id,
      plan_id,
      step.step_id,
      step.agent_id,
      step.task_type,
      now,
    );
    plan_state = recordStepResult(plan_state, exec_record, now);

    // Run dry-run step validation (deps, feature gate, cancellation)
    const dry_run_result = runStepDryRun(
      step,
      { ...dry_run_context, step_outputs },
      completed_step_ids,
      parallel_group_id,
      now,
    );

    if (dry_run_result.dry_run_status === "skipped_optional") {
      // Optional step that failed feature gate — mark as skipped, continue
      const updated_record = transitionStepState(exec_record, "completed", now, {
        initialize_attempted: false,
        initialize_succeeded: false,
      });
      plan_state = recordStepResult(plan_state, updated_record, now);
      completed_step_ids.add(step.step_id);

      step_results.push({
        step_id:           step.step_id,
        agent_id:          step.agent_id,
        task_type:         step.task_type,
        label:             step.label,
        bridge_result: {
          execution_id,
          agent_id:             step.agent_id,
          execution_state:      "completed",
          capability_summary: {
            agent_id:               step.agent_id,
            agent_name:             step.label,
            task_type:              step.task_type,
            required_feature:       request.active_features[0] ?? "ai_gateway",
            required_provider_caps: [],
            supported_task_types:   [step.task_type],
          },
          next_actions:         [],
          approval_required:    false,
          provider_ready:       request.agent_context.gateway.status === "ready",
          initialize_succeeded: false,
          error_message:        "Step skipped — required feature not active",
          execution_timestamp:  now,
          readiness_check:      null, // Guard not run for skipped steps
        },
        execution_state:   "completed",
        parallel_group_id,
        processed_at:      now,
      });
      continue;
    }

    if (
      dry_run_result.dry_run_status === "blocked_dependency" ||
      dry_run_result.dry_run_status === "blocked_feature_gate" ||
      dry_run_result.dry_run_status === "blocked_cancelled" ||
      dry_run_result.dry_run_status === "blocked_gateway"
    ) {
      // Step structurally blocked — cannot prepare lifecycle
      has_step_failed = true;
      const updated_record = transitionStepState(exec_record, "failed", now, {
        initialize_attempted: false,
        initialize_succeeded: false,
        error_message:        dry_run_result.validation_errors.join("; ") || dry_run_result.dry_run_status,
      });
      plan_state = recordStepResult(plan_state, updated_record, now);

      step_results.push({
        step_id:           step.step_id,
        agent_id:          step.agent_id,
        task_type:         step.task_type,
        label:             step.label,
        bridge_result: {
          execution_id,
          agent_id:             step.agent_id,
          execution_state:      "failed",
          capability_summary: {
            agent_id:               step.agent_id,
            agent_name:             step.label,
            task_type:              step.task_type,
            required_feature:       request.active_features[0] ?? "ai_gateway",
            required_provider_caps: [],
            supported_task_types:   [step.task_type],
          },
          next_actions:         ["retry_with_different_input"],
          approval_required:    false,
          provider_ready:       request.agent_context.gateway.status === "ready",
          initialize_succeeded: false,
          error_message:        dry_run_result.validation_errors.join("; ") || `Step blocked: ${dry_run_result.dry_run_status}`,
          execution_timestamp:  now,
          readiness_check:      null, // Guard not run for structurally blocked steps
        },
        execution_state:   "failed",
        parallel_group_id,
        processed_at:      now,
      });
      continue;
    }

    // Step passed validation (dry_run_status === "validated" or "blocked_approval")
    // Run bridge lifecycle preparation — calls agent.initialize() only
    const bridge_ctx = buildStepBridgeContext(request, plan_id, step.step_id, execution_id);
    const bridge_result = await runStepBridgeLifecycle(
      bridge_ctx,
      step,
      effective_policy,
      now,
    );

    const final_state = bridge_result.execution_state;

    // Update execution record with results
    const updated_record = transitionStepState(exec_record, final_state, now, {
      initialize_attempted: bridge_policy.run_initialize,
      initialize_succeeded: bridge_result.initialize_succeeded,
      approval_required:    bridge_result.approval_required,
      provider_ready:       bridge_result.provider_ready,
      error_message:        bridge_result.error_message,
    });
    plan_state = recordStepResult(plan_state, updated_record, now);

    step_results.push({
      step_id:           step.step_id,
      agent_id:          step.agent_id,
      task_type:         step.task_type,
      label:             step.label,
      bridge_result,
      execution_state:   final_state,
      parallel_group_id,
      processed_at:      now,
    });

    if (final_state === "failed") {
      has_step_failed = true;
      continue;
    }

    if (final_state === "awaiting_approval" && bridge_policy.pause_on_approval_required) {
      // Build approval pause record and stop processing further steps
      const remaining_ids = sorted_steps
        .slice(sorted_steps.indexOf(step) + 1)
        .map((s) => s.step_id);
      const pending_ids = computePendingStepIds(
        plan.steps.map((s) => s.step_id),
        completed_step_ids,
        step.step_id,
      );

      approval_pause = buildApprovalPauseRecord(
        plan_id,
        request.dealer_id,
        step.step_id,
        step.agent_id,
        pending_ids.length > 0 ? pending_ids : remaining_ids,
        bridge_result,
        now,
      );

      plan_state = {
        ...plan_state,
        paused_at_step:   step.step_id,
        pending_step_ids: approval_pause.pending_step_ids,
        updated_at:       now,
      };
      continue; // loop terminates next iteration because approval_pause !== null
    }

    // Step ready — mark as completed for dependency tracking
    if (final_state === "ready") {
      completed_step_ids.add(step.step_id);
      step_outputs = writeFeedOutputKeys(step, step_outputs);
    }
  }

  // Compute final plan state
  const all_prepared = step_results.length === plan.steps.length &&
    step_results.every((r) =>
      r.execution_state === "ready" ||
      r.execution_state === "completed" ||
      r.execution_state === "awaiting_approval",
    );

  const overall_state: AIExecutionBridgeState = derivePlanBridgeState(
    plan_state,
    has_step_failed,
    approval_pause !== null,
    all_prepared,
  );

  const steps_prepared = step_results.filter((r) =>
    r.execution_state === "ready" || r.execution_state === "completed",
  ).length;

  const steps_awaiting_approval = step_results.filter((r) =>
    r.execution_state === "awaiting_approval",
  ).length;

  const steps_failed = step_results.filter((r) =>
    r.execution_state === "failed",
  ).length;

  const steps_skipped = step_results.filter((r) => {
    const err = r.bridge_result.error_message;
    return err?.startsWith("Step skipped");
  }).length;

  return {
    plan_id,
    dealer_id:                request.dealer_id,
    workflow_id:              request.workflow_id,
    execution_mode:           "live",
    overall_state,
    step_results,
    approval_paused_at:       approval_pause?.paused_at_step ?? null,
    approval_pause_record:    approval_pause,
    steps_prepared,
    steps_awaiting_approval,
    steps_failed,
    steps_skipped,
    plan_built_at:            now,
    completed_at:             now,
  };
}

// ─── Error path helper ────────────────────────────────────────────────────────

function buildFailedBridgeResult(
  plan_id:     string,
  request:     AILiveRuntimeRequest,
  reason:      string,
  now:         string,
): AIOrchestratorLiveBridgeResult {
  return {
    plan_id,
    dealer_id:              request.dealer_id,
    workflow_id:            request.workflow_id,
    execution_mode:         "live",
    overall_state:          "failed",
    step_results:           [],
    approval_paused_at:     null,
    approval_pause_record:  null,
    steps_prepared:         0,
    steps_awaiting_approval: 0,
    steps_failed:           0,
    steps_skipped:          0,
    plan_built_at:          now,
    completed_at:           now,
  };
  // Note: reason is logged by the caller, not surfaced in the result type.
  void reason;
}
