// DealerOS — Reputation Profile Domain Object
//
// Sprint 11C Phase A: ReputationProfile + ReputationPolicy + ReputationSummary.
//
// ReputationProfile is the dealer-level reputation state object.
// It aggregates:
//   - ReviewDestination[] — where reviews can be directed
//   - ReputationPolicy — governance rules (require_dealer_approval permanently true)
//   - ReputationSummary — aggregated metrics derived from ReviewSignal[]
//   - ReputationInsight[] — AI-derived insights (populated in Phase 11D+)
//
// Security:
//   dealer_id must come from getCurrentDealer() in all server actions.
//   ReputationPolicy.require_dealer_approval is permanently locked to true.
//   No review request may be sent without explicit dealer approval.

import type { ReviewPlatform }                       from "@/lib/ai/agents/reputation/types";
import type {
  ReviewDestination,
  ReputationProfileStatus,
  ReputationTrendDirection,
} from "./reputation-types";

// ─── ReputationPolicy ─────────────────────────────────────────────────────────

/**
 * ReputationPolicy — governance rules for the review request workflow.
 *
 * require_dealer_approval is permanently locked to true and typed as the
 * literal `true` (not `boolean`) to make this invariant enforceable at compile time.
 *
 * Policy defaults are conservative to protect against accidental over-requesting.
 */
export interface ReputationPolicy {
  /** Permanently true — cannot be disabled in any version. */
  require_dealer_approval:             true;
  /**
   * Maximum review requests per customer in a 30-day rolling window.
   * Prevents repeated requests that could feel pressuring. Default: 1.
   */
  max_requests_per_customer_per_30_days: number;
  /**
   * Minimum hours between job completion and review request send.
   * Gives the customer time to reflect before being asked. Default: 24.
   */
  min_hours_after_completion:          number;
  /**
   * Platforms enabled for review requests.
   * Dealer configures these in Settings > Reputation.
   */
  enabled_platforms:                   ReviewPlatform[];
  /**
   * Review requests will only be prepared within this send window.
   * Default: 9 (09:00) — ensures messages arrive during business hours.
   */
  send_window_start_hour:              number;   // 0–23
  /**
   * Review requests will not be sent after this hour.
   * Default: 20 (20:00) — avoids late-night messages.
   */
  send_window_end_hour:                number;   // 0–23
  /**
   * Days to wait for a review response before marking the request "no_response".
   * Default: 14.
   */
  response_window_days:                number;
}

export const DEFAULT_REPUTATION_POLICY: ReputationPolicy = {
  require_dealer_approval:               true,
  max_requests_per_customer_per_30_days: 1,
  min_hours_after_completion:            24,
  enabled_platforms:                     ["google"],
  send_window_start_hour:                9,
  send_window_end_hour:                  20,
  response_window_days:                  14,
};

// ─── ReputationSummary ────────────────────────────────────────────────────────

/**
 * ReputationSummary — aggregated reputation metrics for a dealer.
 * Derived from ReviewSignal[] — never manually set.
 * Null until sufficient data is available (5+ reviews recommended).
 */
export interface ReputationSummary {
  dealer_id:              string;
  total_reviews:          number;
  average_rating:         number;    // 1.0–5.0; 0 if no rated reviews
  rating_distribution:    Partial<Record<1 | 2 | 3 | 4 | 5, number>>;
  /** New reviews received in the last 30 days. */
  review_velocity_30d:    number;
  /** New reviews received in the last 90 days. */
  review_velocity_90d:    number;
  top_platforms:          ReviewPlatform[];
  last_review_at:         string | null;   // ISO 8601
  trend:                  ReputationTrendDirection;
  /** ISO 8601 timestamp when this summary was last computed. */
  computed_at:            string;
}

// ─── ReputationInsight ────────────────────────────────────────────────────────

import type { ReputationInsightType } from "./reputation-types";

/**
 * ReputationInsight — a single piece of AI-derived intelligence.
 * Populated by the reputation_agent in Phase 11D+.
 * In Sprint 11C, the schema is defined but no insights are generated.
 */
export interface ReputationInsight {
  id:            string;
  dealer_id:     string;
  insight_type:  ReputationInsightType;
  /** Human-readable summary of the insight (English, generated by AI in Phase 11D+). */
  summary:       string;
  /** Numeric score relevant to the insight type (e.g., 0–100 sentiment score). */
  score:         number | null;
  trend:         ReputationTrendDirection;
  /** IDs of ReviewSignal objects that contributed to this insight. */
  signal_ids:    string[];
  generated_at:  string;        // ISO 8601
  /** After this date the insight should be regenerated. Null = no expiry. */
  expires_at:    string | null;
}

// ─── ReputationProfile ────────────────────────────────────────────────────────

/**
 * ReputationProfile — the dealer-level reputation management state.
 *
 * The primary business domain object for Sprint 11C.
 * Aggregates all reputation-relevant state for one dealer.
 *
 * dealer_id must always come from getCurrentDealer() in server actions.
 * This object must never be constructed from client-provided dealer_id.
 */
export interface ReputationProfile {
  /** Always from getCurrentDealer() — never from client input. */
  dealer_id:        string;
  shop_name:        string;
  status:           ReputationProfileStatus;
  /**
   * All configured review destinations.
   * Only enabled destinations with a review_url appear in the review request flow.
   */
  destinations:     ReviewDestination[];
  policy:           ReputationPolicy;
  /**
   * Aggregated reputation metrics.
   * Null until at least 5 reviews have been recorded.
   */
  summary:          ReputationSummary | null;
  /**
   * AI-derived insights from reputation analysis.
   * Empty array until Phase 11D+ analysis is implemented.
   */
  insights:         ReputationInsight[];
  created_at:       string;    // ISO 8601
  last_updated_at:  string | null;
}

// ─── Profile helpers ──────────────────────────────────────────────────────────

/**
 * Returns only the enabled ReviewDestinations that have a configured review_url.
 * These are the destinations eligible to receive review requests.
 */
export function getEligibleDestinations(
  profile: ReputationProfile,
): ReviewDestination[] {
  return profile.destinations.filter(
    (d) => d.enabled && d.review_url !== null,
  );
}

/**
 * Returns the primary destination for review requests.
 * Priority: google > website > other enabled platforms.
 * Returns null if no eligible destinations exist.
 */
export function getPrimaryDestination(
  profile: ReputationProfile,
): ReviewDestination | null {
  const eligible = getEligibleDestinations(profile);
  if (eligible.length === 0) return null;
  return (
    eligible.find((d) => d.platform === "google") ??
    eligible.find((d) => d.platform === "website") ??
    eligible[0] ??
    null
  );
}

/**
 * Derives the profile status from the current state of destinations.
 */
export function deriveProfileStatus(
  destinations:   ReviewDestination[],
  totalReviews:   number,
): ReputationProfileStatus {
  const hasEligible = destinations.some(
    (d) => d.enabled && d.review_url !== null,
  );
  if (!hasEligible)      return "pending_setup";
  if (totalReviews < 5)  return "insufficient_data";
  return "active";
}

/**
 * Validates that a ReputationPolicy has sane values.
 * Returns an array of validation error messages (empty = valid).
 */
export function validateReputationPolicy(
  policy: ReputationPolicy,
): string[] {
  const errors: string[] = [];

  if (policy.max_requests_per_customer_per_30_days < 1) {
    errors.push("max_requests_per_customer_per_30_days must be >= 1");
  }
  if (policy.min_hours_after_completion < 0) {
    errors.push("min_hours_after_completion must be >= 0");
  }
  if (policy.send_window_start_hour < 0 || policy.send_window_start_hour > 23) {
    errors.push("send_window_start_hour must be 0–23");
  }
  if (policy.send_window_end_hour < 0 || policy.send_window_end_hour > 23) {
    errors.push("send_window_end_hour must be 0–23");
  }
  if (policy.send_window_start_hour >= policy.send_window_end_hour) {
    errors.push("send_window_start_hour must be less than send_window_end_hour");
  }
  if (policy.response_window_days < 1) {
    errors.push("response_window_days must be >= 1");
  }

  return errors;
}

/**
 * Creates a new ReputationProfile with safe defaults.
 * dealer_id must be provided by the caller from getCurrentDealer().
 */
export function buildDefaultReputationProfile(
  dealerId:  string,
  shopName:  string,
  now:       string,
): ReputationProfile {
  return {
    dealer_id:       dealerId,
    shop_name:       shopName,
    status:          "pending_setup",
    destinations:    [],
    policy:          { ...DEFAULT_REPUTATION_POLICY },
    summary:         null,
    insights:        [],
    created_at:      now,
    last_updated_at: null,
  };
}

/**
 * Constructs a default ReviewDestination for the given platform.
 * review_url must be configured by the dealer before use.
 */
export function buildReviewDestination(
  id:       string,
  dealerId: string,
  platform: ReviewPlatform,
  label:    string,
): ReviewDestination {
  return {
    id,
    dealer_id:     dealerId,
    platform,
    label,
    review_url:    null,   // Must be set in Settings > Reputation
    enabled:       false,  // Disabled until URL is configured
    available_now: true,   // No integration needed — manual URL only
  };
}
