// DealerOS — Review Draft Compliance Model
//
// Sprint 11C Phase C: compliance-first review draft model.
//
// This module defines the ReviewDraft type and the compliance framework
// that governs what can and cannot appear in AI-generated review request messages.
//
// CRITICAL COMPLIANCE RULES (permanently enforced — cannot be weakened):
//
//   1. NO FAKE REVIEWS — The system never generates, submits, or simulates
//      reviews on behalf of customers. All reviews must be written by the customer.
//
//   2. NO STAR RATING SUGGESTIONS — Review requests must never suggest,
//      imply, or request a specific number of stars. The message must invite
//      the customer to share their honest opinion.
//
//   3. NO PRESSURE LANGUAGE — The message must be friendly and optional.
//      No urgency ("今すぐ"), no guilt ("お願いします"), no follow-up pressure.
//
//   4. NO INCENTIVES — Review requests must never offer discounts, gifts,
//      points, or any form of reward in exchange for leaving a review.
//      This violates Google Business Profile and most platform review policies.
//
//   5. VOLUNTARY ALWAYS — The message must explicitly state that the customer
//      is free to write whatever they feel. Include: "率直なご感想で問題ございません".
//
//   6. NO AUTO-POSTING — The system must never submit a review on behalf of a
//      customer via any API, automation, or web scraping.
//
//   7. DEALER APPROVAL REQUIRED — No message may be sent without the dealer
//      explicitly pressing a confirm button. Auto-send is permanently disabled.
//
// These rules are implemented as:
//   - REVIEW_COMPLIANCE_RULES constant (machine-readable rule set)
//   - ReviewComplianceFlag enum (specific violation types)
//   - validateDraftCompliance() function (pattern-based static check)
//   - ReviewDraft.compliance_passed field (must be true before dealer approval)

import type { ReviewPlatform }          from "@/lib/ai/agents/reputation/types";
import type { ReviewComplianceFlag }     from "./reputation-types";

// ─── ReviewDraft ──────────────────────────────────────────────────────────────

/**
 * ReviewDraft — a prepared review request or review response message.
 *
 * Represents the message that will eventually be sent to the customer via LINE
 * (draft_type = "review_request") or posted as a response on a review platform
 * (draft_type = "review_response").
 *
 * Compliance invariants enforced at construction:
 *   - compliance_passed must be true before approval_status can be "approved"
 *   - No message with compliance_flags may be approved
 *   - dealer_approved is always false until explicit dealer confirmation
 */
export interface ReviewDraft {
  id:               string;
  /** The ReviewRequest.id this draft is for. */
  request_id:       string;
  /** Always from getCurrentDealer() — never from client input. */
  dealer_id:        string;
  /** Whether this is an outbound review request or an inbound review response. */
  draft_type:       "review_request" | "review_response";
  /** The message text to be sent or posted. Dealer may edit before approval. */
  message_text:     string;
  character_count:  number;
  platform:         ReviewPlatform;
  /** Direct link to the review page included in the message. Null if not yet configured. */
  review_url:       string | null;
  /**
   * Who generated this draft.
   * "ai" = generated by reputation_agent (Phase 11D+).
   * "dealer" = written manually by the dealer.
   */
  prepared_by:      "ai" | "dealer";
  /** AI provider ID if prepared_by = "ai". Null for dealer-written drafts. */
  ai_provider_id:   string | null;
  approval_status:  "pending" | "approved" | "rejected";
  approved_by:      string | null;
  approved_at:      string | null;
  rejection_reason: string | null;
  /**
   * Compliance violations detected by validateDraftCompliance().
   * Must be empty for compliance_passed to be true.
   */
  compliance_flags: ReviewComplianceFlag[];
  /**
   * True when no compliance flags are present.
   * A draft with compliance_passed = false cannot be approved.
   */
  compliance_passed: boolean;
  created_at:       string;   // ISO 8601
  updated_at:       string;   // ISO 8601
}

// ─── Compliance rule model ────────────────────────────────────────────────────

export interface ReviewComplianceRule {
  id:          ReviewComplianceFlag;
  name:        string;
  description: string;
  severity:    "blocking" | "warning";
  /**
   * Japanese language patterns that trigger this rule.
   * Checked via case-insensitive substring match.
   * These are heuristics — not exhaustive.
   */
  jp_patterns: string[];
  /**
   * English language patterns that trigger this rule.
   */
  en_patterns: string[];
}

/**
 * REVIEW_COMPLIANCE_RULES — machine-readable compliance rule set.
 *
 * These rules are checked by validateDraftCompliance() against any draft message.
 * All "blocking" rules must pass before a draft can be approved.
 *
 * NOTE: These patterns are heuristics for a static pre-check.
 * The AI generation step (Phase 11D+) is also subject to these constraints.
 * Human dealer review remains the final compliance gate.
 */
export const REVIEW_COMPLIANCE_RULES: ReadonlyArray<ReviewComplianceRule> = [
  {
    id:          "star_rating_suggestion",
    name:        "Star Rating Suggestion",
    description: "Draft suggests, requests, or implies a specific star rating.",
    severity:    "blocking",
    jp_patterns: ["5つ星", "五つ星", "★5", "5☆", "最高評価", "高評価", "星5", "満点"],
    en_patterns: ["5 stars", "five stars", "5-star", "highest rating", "top rating"],
  },
  {
    id:          "pressure_language",
    name:        "Pressure Language",
    description: "Draft uses pressure, urgency, or guilt-inducing language.",
    severity:    "blocking",
    jp_patterns: ["ぜひ投稿してください", "必ず", "今すぐ", "期間限定", "お願いします！！", "せめて"],
    en_patterns: ["you must", "please do it now", "urgent", "don't forget to"],
  },
  {
    id:          "incentive_offer",
    name:        "Incentive Offer",
    description: "Draft offers a reward, discount, or gift in exchange for a review.",
    severity:    "blocking",
    jp_patterns: ["割引", "プレゼント", "ポイント", "キャッシュバック", "特典", "お礼", "謝礼", "無料"],
    en_patterns: ["discount", "gift", "reward", "cashback", "free", "bonus", "coupon"],
  },
  {
    id:          "fake_review_attempt",
    name:        "Fake Review Attempt",
    description: "Draft appears to simulate or fabricate a customer review.",
    severity:    "blocking",
    jp_patterns: ["代わりに書き", "代筆", "文例", "このままコピー", "テンプレ"],
    en_patterns: ["copy this review", "paste this", "template review", "write this for you"],
  },
  {
    id:          "auto_post_attempt",
    name:        "Auto-Post Attempt",
    description: "Draft or embedded link attempts to auto-submit a review.",
    severity:    "blocking",
    jp_patterns: ["自動投稿", "ワンクリックで投稿", "自動で送信"],
    en_patterns: ["auto-post", "auto submit", "one-click review"],
  },
] as const;

// ─── Compliance validation ────────────────────────────────────────────────────

export interface DraftComplianceResult {
  passed:           boolean;
  flags:            ReviewComplianceFlag[];
  blocking_flags:   ReviewComplianceFlag[];
  warning_flags:    ReviewComplianceFlag[];
  checked_at:       string;
}

/**
 * Validates a draft message text against REVIEW_COMPLIANCE_RULES.
 *
 * Checks for prohibited patterns using substring matching.
 * This is a fast static pre-check — not a substitute for dealer review.
 *
 * Returns passed = true only when no blocking flags are detected.
 */
export function validateDraftCompliance(
  messageText: string,
  now:         string,
): DraftComplianceResult {
  const foundFlags: ReviewComplianceFlag[] = [];
  const lowerText  = messageText.toLowerCase();

  for (const rule of REVIEW_COMPLIANCE_RULES) {
    const jpMatch = rule.jp_patterns.some((p) => messageText.includes(p));
    const enMatch = rule.en_patterns.some((p) => lowerText.includes(p.toLowerCase()));
    if (jpMatch || enMatch) {
      foundFlags.push(rule.id);
    }
  }

  const blockingFlags = foundFlags.filter((f) => {
    const rule = REVIEW_COMPLIANCE_RULES.find((r) => r.id === f);
    return rule?.severity === "blocking";
  });

  const warningFlags = foundFlags.filter((f) => {
    const rule = REVIEW_COMPLIANCE_RULES.find((r) => r.id === f);
    return rule?.severity === "warning";
  });

  return {
    passed:         blockingFlags.length === 0,
    flags:          foundFlags,
    blocking_flags: blockingFlags,
    warning_flags:  warningFlags,
    checked_at:     now,
  };
}

// ─── Required message elements ────────────────────────────────────────────────

/**
 * ReviewComplianceRequirement — elements that should be present in a review request.
 * These are advisory checks — missing elements trigger warnings, not blocking failures.
 */
export interface ReviewComplianceRequirement {
  element:     string;
  description: string;
  /** Patterns that indicate this element is present. */
  jp_patterns: string[];
  en_patterns: string[];
}

export const REQUIRED_MESSAGE_ELEMENTS: ReadonlyArray<ReviewComplianceRequirement> = [
  {
    element:     "greeting_and_thanks",
    description: "Message should open with a greeting and thank the customer for their business.",
    jp_patterns: ["ありがとう", "感謝", "いつもお世話", "この度は"],
    en_patterns: ["thank you", "thanks for", "appreciate your"],
  },
  {
    element:     "voluntary_freedom",
    description: "Message must explicitly state the customer is free to write their own honest opinion.",
    jp_patterns: ["率直", "ご自由に", "お気持ち", "感じたこと", "自由に"],
    en_patterns: ["honest opinion", "freely", "whatever you feel", "your own words"],
  },
  {
    element:     "explicit_optionality",
    description: "Message must make clear the review is optional.",
    jp_patterns: ["もしよろしければ", "よろしければ", "ご都合がよければ", "お時間があれば"],
    en_patterns: ["if you'd like", "if you have time", "no pressure", "optional"],
  },
] as const;

/**
 * Checks a draft message for the presence of required elements.
 * Returns which required elements are present and which are missing.
 */
export function checkRequiredElements(
  messageText: string,
): { element: string; present: boolean }[] {
  return REQUIRED_MESSAGE_ELEMENTS.map((req) => {
    const jpPresent = req.jp_patterns.some((p) => messageText.includes(p));
    const enPresent = req.en_patterns.some((p) =>
      messageText.toLowerCase().includes(p.toLowerCase()),
    );
    return { element: req.element, present: jpPresent || enPresent };
  });
}

// ─── Draft construction ───────────────────────────────────────────────────────

/**
 * Builds an empty ReviewDraft for dealer manual composition.
 * Use this when the dealer writes the message themselves.
 *
 * The draft starts with compliance_passed = false — validateDraftCompliance()
 * must be called after the message is written.
 */
export function buildEmptyReviewDraft(
  id:         string,
  requestId:  string,
  dealerId:   string,
  platform:   ReviewPlatform,
  reviewUrl:  string | null,
  now:        string,
): ReviewDraft {
  return {
    id,
    request_id:       requestId,
    dealer_id:        dealerId,
    draft_type:       "review_request",
    message_text:     "",
    character_count:  0,
    platform,
    review_url:       reviewUrl,
    prepared_by:      "dealer",
    ai_provider_id:   null,
    approval_status:  "pending",
    approved_by:      null,
    approved_at:      null,
    rejection_reason: null,
    compliance_flags: [],
    compliance_passed: false,
    created_at:       now,
    updated_at:       now,
  };
}

/**
 * Returns a ReviewDraft with updated message text and fresh compliance state.
 * Call this whenever the message_text changes.
 */
export function updateDraftMessage(
  draft:       ReviewDraft,
  messageText: string,
  now:         string,
): ReviewDraft {
  const result = validateDraftCompliance(messageText, now);
  return {
    ...draft,
    message_text:     messageText,
    character_count:  messageText.length,
    compliance_flags: result.flags,
    compliance_passed: result.passed,
    updated_at:       now,
  };
}
